repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort - Sort Python imports (auto-fixes)
        args: [ "--profile", "black", "--filter-files" ]
        exclude: test_example_module.py|run_pipeline.py
  - repo: https://github.com/psf/black
    rev: 24.8.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: black - consistent Python code formatting (auto-fixes)
        language_version: python # Should be a command that runs python3.6+
        exclude: src/api/insert.py|main.py
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 - Python linting
        exclude: main.py|src/api/insert.py
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets - Detect secrets in staged code
        args: [ "--baseline", ".secrets.baseline" ]
        exclude: .*/tests/.*
