# config.yaml

##########################################################################################

# LOGGING
logging:
  root_level: INFO
  file_level: INFO
  console_level: INFO

##########################################################################################
