# config.yaml

##########################################################################################

# LOGGING
logging:
  root_level: DEBUG
  file_level: DEBUG
  console_level: INFO

##########################################################################################
